-- GENERATED by `python -m tools.export_uc_ddl` — DO NOT EDIT BY HAND.
--
-- Sources of truth:
--   * column names/types : the dbt-built DuckDB schema (duckdb schema `gold`)
--   * MERGE keys          : sync/push_gold_to_turso.py::GOLD_TABLES
--   * never-updated cols  : sync/push_gold_to_turso.py::ML_OWNED_COLUMNS
--
-- Consumed by databricks/jobs/merge_gold.py: idempotent CREATEs, one
-- key-matched MERGE per table (staging view name: stg_<table>).
-- CI runs `python -m tools.export_uc_ddl --check` for staleness.

CREATE SCHEMA IF NOT EXISTS terrasentinel.gold;

CREATE TABLE IF NOT EXISTS terrasentinel.gold.gold_fire_anomalies (
    region_id STRING,
    observation_date DATE,
    detection_count BIGINT,
    h3_cell_count BIGINT,
    high_confidence_count DECIMAL(38,0),
    frp_sum DOUBLE,
    frp_max DOUBLE,
    frp_mean DOUBLE,
    confidence_pct_mean DOUBLE,
    night_detection_share DOUBLE,
    cell_concentration DOUBLE,
    frp_per_detection DOUBLE,
    night_detection_count DECIMAL(38,0),
    satellite_count BIGINT,
    max_cell_detections BIGINT,
    baseline_median DOUBLE,
    baseline_mad DOUBLE,
    baseline_scale DOUBLE,
    baseline_samples BIGINT,
    baseline_years BIGINT,
    baseline_method STRING,
    zscore DOUBLE,
    is_anomaly BOOLEAN,
    severity STRING,
    anomaly_score DOUBLE,
    model_version STRING,
    scored_at TIMESTAMP,
    updated_at TIMESTAMP
) COMMENT 'gold_fire_anomalies | upsert keys: region_id, observation_date | ML-owned (untouched by this merge): anomaly_score, model_version, scored_at';

MERGE INTO terrasentinel.gold.gold_fire_anomalies AS target
USING stg_gold_fire_anomalies AS source
ON target.region_id = source.region_id
AND target.observation_date = source.observation_date
WHEN MATCHED THEN UPDATE SET
    region_id = source.region_id,
    observation_date = source.observation_date,
    detection_count = source.detection_count,
    h3_cell_count = source.h3_cell_count,
    high_confidence_count = source.high_confidence_count,
    frp_sum = source.frp_sum,
    frp_max = source.frp_max,
    frp_mean = source.frp_mean,
    confidence_pct_mean = source.confidence_pct_mean,
    night_detection_share = source.night_detection_share,
    cell_concentration = source.cell_concentration,
    frp_per_detection = source.frp_per_detection,
    night_detection_count = source.night_detection_count,
    satellite_count = source.satellite_count,
    max_cell_detections = source.max_cell_detections,
    baseline_median = source.baseline_median,
    baseline_mad = source.baseline_mad,
    baseline_scale = source.baseline_scale,
    baseline_samples = source.baseline_samples,
    baseline_years = source.baseline_years,
    baseline_method = source.baseline_method,
    zscore = source.zscore,
    is_anomaly = source.is_anomaly,
    severity = source.severity,
    updated_at = source.updated_at
WHEN NOT MATCHED THEN INSERT (region_id, observation_date, detection_count, h3_cell_count, high_confidence_count, frp_sum, frp_max, frp_mean, confidence_pct_mean, night_detection_share, cell_concentration, frp_per_detection, night_detection_count, satellite_count, max_cell_detections, baseline_median, baseline_mad, baseline_scale, baseline_samples, baseline_years, baseline_method, zscore, is_anomaly, severity, updated_at)
    VALUES (source.region_id, source.observation_date, source.detection_count, source.h3_cell_count, source.high_confidence_count, source.frp_sum, source.frp_max, source.frp_mean, source.confidence_pct_mean, source.night_detection_share, source.cell_concentration, source.frp_per_detection, source.night_detection_count, source.satellite_count, source.max_cell_detections, source.baseline_median, source.baseline_mad, source.baseline_scale, source.baseline_samples, source.baseline_years, source.baseline_method, source.zscore, source.is_anomaly, source.severity, source.updated_at);

CREATE TABLE IF NOT EXISTS terrasentinel.gold.gold_ice_extent_trends (
    region_id STRING,
    period_start DATE,
    metric_type STRING,
    baseline_source STRING,
    value DOUBLE,
    baseline_mean DOUBLE,
    baseline_stddev DOUBLE,
    baseline_samples INT,
    latitude DOUBLE,
    longitude DOUBLE,
    zscore DOUBLE,
    is_anomaly BOOLEAN,
    severity STRING,
    anomaly_score DOUBLE,
    model_version STRING,
    scored_at TIMESTAMP,
    updated_at TIMESTAMP
) COMMENT 'gold_ice_extent_trends | upsert keys: region_id, period_start | ML-owned (untouched by this merge): anomaly_score, model_version, scored_at';

MERGE INTO terrasentinel.gold.gold_ice_extent_trends AS target
USING stg_gold_ice_extent_trends AS source
ON target.region_id = source.region_id
AND target.period_start = source.period_start
WHEN MATCHED THEN UPDATE SET
    region_id = source.region_id,
    period_start = source.period_start,
    metric_type = source.metric_type,
    baseline_source = source.baseline_source,
    value = source.value,
    baseline_mean = source.baseline_mean,
    baseline_stddev = source.baseline_stddev,
    baseline_samples = source.baseline_samples,
    latitude = source.latitude,
    longitude = source.longitude,
    zscore = source.zscore,
    is_anomaly = source.is_anomaly,
    severity = source.severity,
    updated_at = source.updated_at
WHEN NOT MATCHED THEN INSERT (region_id, period_start, metric_type, baseline_source, value, baseline_mean, baseline_stddev, baseline_samples, latitude, longitude, zscore, is_anomaly, severity, updated_at)
    VALUES (source.region_id, source.period_start, source.metric_type, source.baseline_source, source.value, source.baseline_mean, source.baseline_stddev, source.baseline_samples, source.latitude, source.longitude, source.zscore, source.is_anomaly, source.severity, source.updated_at);

CREATE TABLE IF NOT EXISTS terrasentinel.gold.gold_h3_fire (
    source_id STRING,
    region_id STRING,
    h3_index STRING,
    latitude DOUBLE,
    longitude DOUBLE,
    period_start DATE,
    period_grain STRING,
    metric_type STRING,
    spatial_scope STRING,
    value DOUBLE,
    high_confidence_count DOUBLE,
    baseline_mean DOUBLE,
    updated_at TIMESTAMP
) COMMENT 'gold_h3_fire | upsert keys: h3_index, period_start, metric_type';

MERGE INTO terrasentinel.gold.gold_h3_fire AS target
USING stg_gold_h3_fire AS source
ON target.h3_index = source.h3_index
AND target.period_start = source.period_start
AND target.metric_type = source.metric_type
WHEN MATCHED THEN UPDATE SET
    source_id = source.source_id,
    region_id = source.region_id,
    h3_index = source.h3_index,
    latitude = source.latitude,
    longitude = source.longitude,
    period_start = source.period_start,
    period_grain = source.period_grain,
    metric_type = source.metric_type,
    spatial_scope = source.spatial_scope,
    value = source.value,
    high_confidence_count = source.high_confidence_count,
    baseline_mean = source.baseline_mean,
    updated_at = source.updated_at
WHEN NOT MATCHED THEN INSERT (source_id, region_id, h3_index, latitude, longitude, period_start, period_grain, metric_type, spatial_scope, value, high_confidence_count, baseline_mean, updated_at)
    VALUES (source.source_id, source.region_id, source.h3_index, source.latitude, source.longitude, source.period_start, source.period_grain, source.metric_type, source.spatial_scope, source.value, source.high_confidence_count, source.baseline_mean, source.updated_at);

CREATE TABLE IF NOT EXISTS terrasentinel.gold.gold_h3_sst (
    source_id STRING,
    region_id STRING,
    h3_index STRING,
    latitude DOUBLE,
    longitude DOUBLE,
    period_start DATE,
    period_grain STRING,
    metric_type STRING,
    spatial_scope STRING,
    value DOUBLE,
    high_confidence_count DOUBLE,
    baseline_mean DOUBLE,
    updated_at TIMESTAMP
) COMMENT 'gold_h3_sst | upsert keys: h3_index, period_start, metric_type';

MERGE INTO terrasentinel.gold.gold_h3_sst AS target
USING stg_gold_h3_sst AS source
ON target.h3_index = source.h3_index
AND target.period_start = source.period_start
AND target.metric_type = source.metric_type
WHEN MATCHED THEN UPDATE SET
    source_id = source.source_id,
    region_id = source.region_id,
    h3_index = source.h3_index,
    latitude = source.latitude,
    longitude = source.longitude,
    period_start = source.period_start,
    period_grain = source.period_grain,
    metric_type = source.metric_type,
    spatial_scope = source.spatial_scope,
    value = source.value,
    high_confidence_count = source.high_confidence_count,
    baseline_mean = source.baseline_mean,
    updated_at = source.updated_at
WHEN NOT MATCHED THEN INSERT (source_id, region_id, h3_index, latitude, longitude, period_start, period_grain, metric_type, spatial_scope, value, high_confidence_count, baseline_mean, updated_at)
    VALUES (source.source_id, source.region_id, source.h3_index, source.latitude, source.longitude, source.period_start, source.period_grain, source.metric_type, source.spatial_scope, source.value, source.high_confidence_count, source.baseline_mean, source.updated_at);

CREATE TABLE IF NOT EXISTS terrasentinel.gold.gold_deforestation_index (
    region_id STRING,
    month_start DATE,
    ndvi_mean DOUBLE,
    ndvi_stddev DOUBLE,
    ndvi_min DOUBLE,
    ndvi_max DOUBLE,
    ndvi_prior_year DOUBLE,
    ndvi_change DOUBLE,
    change_mean DOUBLE,
    change_stddev DOUBLE,
    change_samples BIGINT,
    change_zscore DOUBLE,
    is_anomaly BOOLEAN,
    severity STRING,
    observation_count DECIMAL(38,0),
    cloud_pct_mean DOUBLE,
    anomaly_score DOUBLE,
    model_version STRING,
    scored_at TIMESTAMP,
    updated_at TIMESTAMP
) COMMENT 'gold_deforestation_index | upsert keys: region_id, month_start | ML-owned (untouched by this merge): anomaly_score, model_version, scored_at';

MERGE INTO terrasentinel.gold.gold_deforestation_index AS target
USING stg_gold_deforestation_index AS source
ON target.region_id = source.region_id
AND target.month_start = source.month_start
WHEN MATCHED THEN UPDATE SET
    region_id = source.region_id,
    month_start = source.month_start,
    ndvi_mean = source.ndvi_mean,
    ndvi_stddev = source.ndvi_stddev,
    ndvi_min = source.ndvi_min,
    ndvi_max = source.ndvi_max,
    ndvi_prior_year = source.ndvi_prior_year,
    ndvi_change = source.ndvi_change,
    change_mean = source.change_mean,
    change_stddev = source.change_stddev,
    change_samples = source.change_samples,
    change_zscore = source.change_zscore,
    is_anomaly = source.is_anomaly,
    severity = source.severity,
    observation_count = source.observation_count,
    cloud_pct_mean = source.cloud_pct_mean,
    updated_at = source.updated_at
WHEN NOT MATCHED THEN INSERT (region_id, month_start, ndvi_mean, ndvi_stddev, ndvi_min, ndvi_max, ndvi_prior_year, ndvi_change, change_mean, change_stddev, change_samples, change_zscore, is_anomaly, severity, observation_count, cloud_pct_mean, updated_at)
    VALUES (source.region_id, source.month_start, source.ndvi_mean, source.ndvi_stddev, source.ndvi_min, source.ndvi_max, source.ndvi_prior_year, source.ndvi_change, source.change_mean, source.change_stddev, source.change_samples, source.change_zscore, source.is_anomaly, source.severity, source.observation_count, source.cloud_pct_mean, source.updated_at);

CREATE TABLE IF NOT EXISTS terrasentinel.gold.gold_glacier_backscatter (
    region_id STRING,
    period_start DATE,
    metric_type STRING,
    baseline_source STRING,
    value DOUBLE,
    baseline_mean DOUBLE,
    baseline_stddev DOUBLE,
    baseline_samples BIGINT,
    latitude DOUBLE,
    longitude DOUBLE,
    zscore DOUBLE,
    is_anomaly BOOLEAN,
    severity STRING,
    anomaly_score DOUBLE,
    model_version STRING,
    scored_at TIMESTAMP,
    updated_at TIMESTAMP
) COMMENT 'gold_glacier_backscatter | upsert keys: region_id, period_start | ML-owned (untouched by this merge): anomaly_score, model_version, scored_at';

MERGE INTO terrasentinel.gold.gold_glacier_backscatter AS target
USING stg_gold_glacier_backscatter AS source
ON target.region_id = source.region_id
AND target.period_start = source.period_start
WHEN MATCHED THEN UPDATE SET
    region_id = source.region_id,
    period_start = source.period_start,
    metric_type = source.metric_type,
    baseline_source = source.baseline_source,
    value = source.value,
    baseline_mean = source.baseline_mean,
    baseline_stddev = source.baseline_stddev,
    baseline_samples = source.baseline_samples,
    latitude = source.latitude,
    longitude = source.longitude,
    zscore = source.zscore,
    is_anomaly = source.is_anomaly,
    severity = source.severity,
    updated_at = source.updated_at
WHEN NOT MATCHED THEN INSERT (region_id, period_start, metric_type, baseline_source, value, baseline_mean, baseline_stddev, baseline_samples, latitude, longitude, zscore, is_anomaly, severity, updated_at)
    VALUES (source.region_id, source.period_start, source.metric_type, source.baseline_source, source.value, source.baseline_mean, source.baseline_stddev, source.baseline_samples, source.latitude, source.longitude, source.zscore, source.is_anomaly, source.severity, source.updated_at);

CREATE TABLE IF NOT EXISTS terrasentinel.gold.gold_h3_sentinel (
    source_id STRING,
    region_id STRING,
    h3_index STRING,
    latitude DOUBLE,
    longitude DOUBLE,
    period_start DATE,
    period_grain STRING,
    metric_type STRING,
    spatial_scope STRING,
    value DOUBLE,
    high_confidence_count DOUBLE,
    baseline_mean DOUBLE,
    updated_at TIMESTAMP
) COMMENT 'gold_h3_sentinel | upsert keys: h3_index, period_start, metric_type';

MERGE INTO terrasentinel.gold.gold_h3_sentinel AS target
USING stg_gold_h3_sentinel AS source
ON target.h3_index = source.h3_index
AND target.period_start = source.period_start
AND target.metric_type = source.metric_type
WHEN MATCHED THEN UPDATE SET
    source_id = source.source_id,
    region_id = source.region_id,
    h3_index = source.h3_index,
    latitude = source.latitude,
    longitude = source.longitude,
    period_start = source.period_start,
    period_grain = source.period_grain,
    metric_type = source.metric_type,
    spatial_scope = source.spatial_scope,
    value = source.value,
    high_confidence_count = source.high_confidence_count,
    baseline_mean = source.baseline_mean,
    updated_at = source.updated_at
WHEN NOT MATCHED THEN INSERT (source_id, region_id, h3_index, latitude, longitude, period_start, period_grain, metric_type, spatial_scope, value, high_confidence_count, baseline_mean, updated_at)
    VALUES (source.source_id, source.region_id, source.h3_index, source.latitude, source.longitude, source.period_start, source.period_grain, source.metric_type, source.spatial_scope, source.value, source.high_confidence_count, source.baseline_mean, source.updated_at);
